pkg/keystorev3/walletfile.go

The commit message was bigger than the diff. But an important fix, nonetheless.

Fix aes-128-ctr cipher name

---

pkg/abi/typecomponents.go
pkg/abi/typecomponents_test.go

While writing the code in FireFly core to traverse the component tree, these three fields present on the `abi` are needed as well. I solved this by attaching the original `Parameter` to the `TypeComponent` struct/interface.

Expose ABI Parameter on TypeComponent

---

pkg/abi/abi.go
pkg/abi/abi_test.go

- Renames `GenerateID()` to `GenerateFunctionSelector()`
- Adds `SignatureHash()` as that computes the hash of a function signature

[signature-hash] renaming GenerateID and adding signatureHash

---

.gitignore
.vscode/settings.json
internal/signermsgs/en_api_translations.go
internal/signermsgs/en_error_messges.go
pkg/abi/abidecode.go
pkg/abi/typecomponents.go
pkg/abi/typecomponents_test.go
pkg/ffi2abi/ffi.go
pkg/ffi2abi/ffi_test.go

Here's my proposal for how to address my suggestion in https://github.com/hyperledger/firefly-signer/pull/9#discussion_r905462373
Note I filled in the gap on the floating point input, with a `oneOf` there, and this means the test fails due to `number` being missing from: https://github.com/hyperledger/firefly-common/blob/7f6b2eaf8066c146f377864981e92ea9e1f43903/pkg/fftypes/ffi_param_validator.go#L54-L58
> PR submitted here for common: https://github.com/hyperledger/firefly-common/pull/21

Proposal to standardize elementary type info in the abi package

---

Makefile
pkg/ethsigner/transaction.go
pkg/ethsigner/transaction_test.go

Allows for the various types of transaction (origin, EIP-155, EIP-1559) the hash payload, and transaction hash, to be calculated independently of performing signing.

Add features for calculating hashes of transactions

---

pkg/ethsigner/transaction.go
pkg/secp256k1/keypair.go
pkg/secp256k1/signer.go

In addition to the existing secp256k1 local signer,
we can allow any provider/api that has signature generation capability
to implement the Signer interface and use firefly-signer's transaction
signing
Signed-off-by: Vinod Damle <vinod.damle@kaleido.io>

Add Signer interface to support multiple Signers

---

Makefile
internal/rpcbackend/backend.go
internal/rpcserver/rpchandler.go
internal/rpcserver/rpchandler_test.go
internal/rpcserver/rpcprocessor.go
internal/rpcserver/rpcprocessor_test.go
internal/rpcserver/server.go
internal/signermsgs/en_error_messges.go
mocks/rpcbackendmocks/backend.go
pkg/rpcbackend/backend.go
pkg/rpcbackend/backend_test.go

We had some duplicated code between `firefly-evmconnect` and `firefly-signer`. This PR moves the updated RPC error handling and logging from evmconnect into signer, and exposes it as a shared package. I'm about to open a subsequent PR for evmconnect that uses this package so there is one place this code exists now instead of two.

Move RPC Client code to shared package

---

pkg/ethsigner/transaction.go

https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_sendtransaction with `value` being an optional field, this will prevent it from being serialized and passed through in JSONRPC requests when set to `nil`.
We encountered https://github.com/hyperledger/firefly-evmconnect passing `nil` `value` down to our managed signer which passed it along to the chain and received an RPC error as a result:
```
[2022-08-24T21:06:20.566Z]  INFO id=29337 method=eth_sendTransaction params=[map[data:0x48ce1dcce6ba6ce9bbd44a5a955d32e79d5f6d9d38559556a2364b60933c0ab216077c8a1cbf6f208b2b0afa8bf5b242388dca09a30d32af1b7adcc604d53f4b05d2b50c000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000000000000000000000 …
```

omitempty Value and Gas for ethsigner.Transaction

---

pkg/rpcbackend/backend.go

See https://github.com/hyperledger/firefly-evmconnect/issues/26
So we have logs like this if only INFO logging is enabled:
```
RPC[2->000012346] <-- eth_getTransactionByHash [200] OK (1.43ms)
```

Update info logging to include method and time

---

pkg/ffi2abi/ffi_param_validator.go
pkg/ffi2abi/ffi_param_validator_test.go

Resolves https://github.com/hyperledger/firefly-signer/issues/25
I was able to compile FireFly locally using a go.mod replace and verified that this fixes the incorrectly rejected FFI that I was seeing before.

Fix Ethereum FFIParamValidator to allow oneOf syntax for basic types

---

pkg/fswallet/fslistener.go

In a Linux environment with a Samba mounted CIFS filesystem, we only seem to get a notification as follows:
```
[2022-10-18T20:52:51.713Z] TRACE FSEvent [WRITE]: /.../keystore/UTC--2022-10-18T20-52-51.648Z-07686308b652040e74189f7a63a0031e6391e234 fswallet=/.../keystore
```
Currently the code only evaluates `CREATE` events, so we need to take the small overhead of the extra `stat()` and filename matching of also handling `WRITE` events.

Evaluate all FS events: SMB CIFS filesystems mounted do not notify `CREATE`

---

internal/rpcserver/rpcprocessor.go
internal/rpcserver/rpcprocessor_test.go
internal/rpcserver/server.go
internal/rpcserver/server_test.go
mocks/rpcbackendmocks/backend.go
pkg/rpcbackend/backend.go
pkg/rpcbackend/backend_test.go

Signed-off-by: Jim Zhang <jim.zhang@kaleido.io>

Use RPCError as return from CallRPC() to catch error details

---

internal/signermsgs/en_error_messges.go
pkg/rpcbackend/backend.go
pkg/rpcbackend/backend_test.go

Correct invalid assumption in https://github.com/hyperledger/firefly-signer/pull/43 and provide a more helpful error on parse result failures.

Separate error for parse result

---

pkg/abi/abidecode.go
pkg/abi/abidecode_test.go
pkg/abi/abiencode.go

This fixes https://github.com/hyperledger/firefly/issues/1323
I took a a look at this issue and turns out that when a Solidity struct is encoded in RLP and the type in the ABI is a tuple the resulting RLP doesn't have a variable ABI length block.
For the struct in Solidity contract:
```
struct AccountBalance {
address account;
uint balance;
}
```
We get the RLP
```
000000000000000000000000d2d8a61d774f552301d71aa99a78aff2e4765ca7 // address value
000000000000000000000000000000000000000000000000000000000000007b // balance value
```
After chatting with @peterbroadhurst  we determined based on the spec what a dynamic tuple means. A tuple is dynamic if any of its elements are dynamic! In this case the tuple isn't since `address` and `uint` are not dynamic.
The code was always treating a …

fix: check dynamic type for tuple before decoding

---

.golangci.yml
config.md
go.mod
go.sum
pkg/rpcbackend/backend.go

```go
// In all return paths *including error paths* the RPCResponse is populated
```
... we say it, but then we return `nil` if the context is closed

Ensure SyncRequest never returns nil, even if context is closed 

---

.golangci.yml
config.md
go.mod
go.sum
internal/signermsgs/en_error_messges.go
pkg/ethereum/ethereum.go
pkg/ethtypes/hexinteger.go
pkg/ethtypes/hexinteger_test.go
pkg/rpcbackend/backend.go
pkg/rpcbackend/wsbackend.go
pkg/rpcbackend/wsbackend_test.go

This PR adds a JSONRPC WebSocket client.
- Provides sync `CallRPC` functionality over an async WebSocket transport
- Manages JSON/RPC request IDs for you
- Provides automatic reconnect, and all the other quality of life benefits of the `firefly-common` WebSocket impl
- Supports `eth_subscribe`/`eth_unsubscribe` with a higher level `Subscription` semantic
- Automatically resubscribes if your WebSocket reconnects
- Has a client-side ID to track your subscription, as well as the server-side ID (which changes on reconnect)
- At-most-once delivery semantics is all you get with raw Ethereum WebSockets (it's all the `eth_` protocol supports) - you miss it, you lose it
- If you need more than that, use the full [FireFly core](https://github.com/kaleido-io/firefly) which provides reliable …

Add wsbackend client

---

pkg/rpcbackend/backend.go

This should resolve https://github.com/hyperledger/firefly-evmconnect/issues/103 after it's included in EVMConnect

Additional nil check on CallRPC

---

pkg/rpcbackend/wsbackend.go

In the case of a reconnect the `resChl` was `nil` so sending `nil` to it ended up blocking, causing the receiver to not receive any further messages.

Fix auto reconnect for RPC WebSocket

---

pkg/ethereum/ethereum.go

Having a mix of capitalization was causing some issues in a variety of ways. This change normalizes to lowercase, and then leaves it up to the calling code if it wants to display and address with a checksum or not.

Update receipts and TX info

---

pkg/abi/abidecode.go
pkg/abi/abidecode_test.go
pkg/abi/typecomponents.go

ref: https://discordapp.com/channels/905194001349627914/928377875827154984/1194272891957694614
When indexing the BSC chain, it's been reported that the EVM connector crashes when indexing [this transaction](https://bscscan.com/tx/0x26a81f0d1aa4149627ca98ab8ac457b18ffe47f1d332676cf0747c6c36194ade). This is because the padding scheme used in the transaction is not using zero-bytes to pad out the value. When we parse the entire 32 bytes from the chunk into an integer, the padding non-zero bytes are contributing to the integer value, causing the parsed address value to overflow what can be actually been shown in 20 bytes. This issue is causing golang to panic and the EVM connector to crash.
The proposed fix is to decode addresses only on the right-most 20 bytes, and ignore the front 12 bytes …

fix: when decoding addresses restrict to 20 bytes

---

pkg/abi/abidecode_test.go
pkg/abi/inputparsing.go
pkg/abi/typecomponents.go
pkg/eip712/typed_data_v4.go
pkg/eip712/typed_data_v4_test.go
pkg/ethsigner/transaction.go
pkg/ethtypes/hexbytes.go
pkg/ethtypes/hexbytes_test.go
pkg/ethtypes/hexuint64.go
pkg/ethtypes/hexuint64_test.go
pkg/keystorev3/aes128ctr.go
pkg/keystorev3/pbkdf2.go
pkg/keystorev3/scrypt.go
pkg/keystorev3/wallet.go
pkg/keystorev3/wallet_test.go
pkg/keystorev3/walletfile.go
pkg/rpcbackend/backend.go
pkg/rpcbackend/wsbackend.go
pkg/secp256k1/signer.go

- Allows use of the EIP-712 hashing algorithm for the data itself, without needing to also supply a domin.
- Allows querying `M` and `N` dimensions of parsed Elementary Types
- Fixes issue where we could have a `Component` array containing a nil entry on the case of extra parameters on input
- Allows `Recover` functions to determine the original payload of the transactions, as well as the recovered signature
- Allows raw signing key access, as well as `secp256k1` curve-adapted access, to private key materials from `keystorev3`
- Ensures errors from serializing inputs are returned

Expose API to directly call HashStruct from EIP-712 and M+N dims

---

pkg/keystorev3/pbkdf2.go
pkg/keystorev3/pbkdf2_test.go
pkg/keystorev3/scrypt.go
pkg/keystorev3/scrypt_test.go
pkg/keystorev3/wallet.go
pkg/keystorev3/wallet_test.go
pkg/keystorev3/walletfile.go
pkg/secp256k1/keypair.go

As discussed in #69:
- The `address` field is **not** part of the Version 3 spec - was removed [here](https://github.com/ethereum/wiki/wiki/Web3-Secret-Storage-Definition#alterations-from-version-1) justification:
> `Address` unnecessary and compromises privacy.
- The `address` field is a very Ethereum specific way to store a piece of metadata that is intended to identify the private key publicly
- An `0x` prefixed 20 hex-byte compressed identifier of the SECP256K1 derivied public key, for the private key
- When this library is used to stored key materials for other curves/cryptogrpahy (as now supported since #68) its misleading
So...
This PR allows `WalletFile.Metadata()` to be called get a `map[string]any` that you can used to:
1. store arbitrary additional fields, like `bjjIdentifer` …

Allow additional/override of non-spec fields, including "address"

---

.github/workflows/docker_main.yml

Due to new changes the GitHub Token in the action no longer has the write permissions and thus the actions fail when pushing the docker image to `ghcr.io`.  To enable the GitHub token to have those permissions, it now needs to be specified within the job itself.
403 forbidden error https://github.com/hyperledger/firefly-signer/actions/runs/10359460639
```
The push refers to repository [ghcr.io/hyperledger/firefly-signer]
fecdbc4471ce: Preparing
31d7a001c31a: Preparing
96bc1885c3ff: Preparing
6f697f52d485: Preparing
denied: installation not allowed to Write organization package
```

Add correct permissions for action

---

config.md
go.mod
go.sum
pkg/abi/inputparsing.go
pkg/abi/inputparsing_test.go

This PR relates to `firefly-common` PR https://github.com/hyperledger/firefly-common/pull/147
That PR introduces support for large JSON numbers where previously they would be limited to the size of `float64` `2^64-1`. This is particularly useful when dealing with the scale of numeric parameters typical of Ethereum smart contracts. See PR https://github.com/hyperledger/firefly-common/pull/147 for more information.
This `firefly-signer` PR does 2 things:
1. Pulls in the latest version of `firefly-common` to utilize the new large number support
2. Adds a fallback approach to parsing strings to handle scientific notation numbers e.g. `1e+25`.

Add support for 256 bit JSON numbers (vs. strings), including scientific notation

---

pkg/abi/abi.go
pkg/abi/abi_test.go
pkg/abi/typecomponents.go
pkg/rpcbackend/backend.go

After all the work in #71, I ended up missing one of the most important distinguishing things the feature was meant to help with 🤦 
The ABI signature of an event is identical for ERC-20/ERC-721, but some of the fields are indexed. I'd missed including that.
In PR chain with #73

Solsig indexed

---

pkg/abi/abi.go
pkg/abi/abi_test.go
pkg/abi/signedi256.go
pkg/abi/typecomponents.go

A helpful utility for custom errors, to let you send `revertData` to the function, and get back a string like:
`ExampleError("test1","12345")`
or for default `revert("some string")`
`Error("some string")`

Add utility for parsing errors, including as a string

---

internal/signermsgs/en_error_messges.go
pkg/abi/abi.go
pkg/abi/abi_test.go
pkg/abi/inputparsing.go
pkg/abi/inputparsing_test.go
pkg/abi/signedi256.go
pkg/abi/typecomponents.go

In PR chain with #82 
We were throwing an error in the case that you supplied an input like `{"0":12345}` to an ABI with an unnamed parameter, but on output we were perfectly accepting that values could have unnamed parameters and we did translation to `0` in the object syntax.
This PR makes us consistent in both directions.
It's a change in behavior, but only from returning an error, to having a defined behavior.

Handle unnamed tuple entries consistently on input and output

---

pkg/abi/abi.go
pkg/abi/abi_test.go
pkg/abi/outputserialization.go
pkg/abi/outputserialization_test.go

Note this does not do anything with `fixed` and `ufixed` types, which are really a theoretical thing as they aren't supported by solidity yet (/ever).
When we go back to these, we need to change the internal storage to `big.Int` rather than `big.Float` as otherwise there's a risk of loss of precision.

Fix negative integer hex formatting and add JSON number formatting option

---

pkg/abi/abi.go
pkg/ethsigner/transaction.go
pkg/ethsigner/transaction_test.go

Couple of API enhancements:
- Ability to format errors separately to detecting them, including fixing the formatting of addresses in those strings
- Ability to round-trip the transaction data for EIP-1559, without signing

Allow formatting of string errors separately from matching

---

config.md
go.mod
go.sum
pkg/fswallet/fslistener.go
pkg/fswallet/fslistener_test.go
pkg/fswallet/fswallet.go
pkg/fswallet/fswallet_test.go

Currently there's an async notification system for keys, which pushes to a channel during initialization or refresh.
I have cases where I want to use this module in a way that is deterministic about knowing if a key does/doesn't exist - and that means I cannot complete initialization (and start up my server) until I know I've added all the keys that exist to my map.
For that I need a synchronous callback option.

Provide synchronous init option for FS wallet

---

pkg/fswallet/config.go
pkg/fswallet/fslistener_test.go
pkg/fswallet/fswallet.go
pkg/fswallet/fswallet_ethaddr.go
pkg/fswallet/fswallet_test.go

The FS Wallet feature is very useful for managing on-disk wallets, but you currently have to use the Ethereum Address to reference the KeystoreV3 files.
This is odd in cases where using this library for signing with different Web3 ecosystems, such as when building connectors for FireFly to those ecosystems.
So this PR decouples the Eth specific layer (no change to API) from the generic underlying layer (new direct API for this).

Add support for using the FileSystem Wallet without using EthAddress
